### ISSUE TITLE
[Wishlist] Typescript declaration file *.d.ts

### ISSUE THREAD

**Issue by stephen-smith** [francisrstokes/arcsecond#25] opened 2019-11-30 06:32 UTC
Would have kept me from making some dumb mistakes with map today.  Also, strict null checking can be useful with possibly / endOfInput.

**Comment by francisrstokes** [comment] 2019-11-30 10:09
Hey Stephen - the types is something that I'm working on actually - they'll come out in the next major version.

For the null checking, I'm not sure I know what you mean? Can you elaborate? (probably should be a separate issue)

**Comment by stephen-smith** [comment] 2019-11-30 21:52
If you get the types right under the "--strictNullChecks" (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html), then the types and null checking will go hand-in-hand.  That's all I meant for null checking.

**Comment by jeffrose** [comment] 2019-12-05 20:13
I started a type declaration as well. I can share what I have if you're interested.

**Comment by IMax153** [comment] 2019-12-07 16:57
@francisrstokes @jeffrose I would be happy to contribute to type declarations as well if help would be appreciated.

**Comment by jeffrose** [comment] 2019-12-11 20:52
I've never actually written a `.d.ts` file from scratch before. I typically just code in TypeScript and let the compiler generate them.

My use of generics may be a little overzealous. I'm also not as familiar with internals of arcsecond, so some of what is described below may not be accurate yet.

```typescript
declare namespace Arcsecond {

    type ParserState<TResult = string, TData = void> = {
        isError: boolean;
        error: string;
        target: string;
        data: TData;
        index: number;
        result: TResult;
    };

    type StateData<TResult = string, TData = void> = {
        result: TResult;
        data: TData;
    };

    type ChainCallback<T> = ( result: T ) => Parser<T, U>;
    type ChainFromDataCallback<T, U> = ( state: StateData<T, U> ) => Parser<T, U>;
    type ErrorChainCallback<T> = ( error: string, index: number, data: U ) => ParserState<T, U>;
    type ErrorMapCallback<T> = ( error: string, index: number, data: T ) => string;
    type ForkErrorCallback<T> = ( error: string, newState: ParserState<T, U> ) => ParserState<T, U>;
    type ForkSuccessCallback<T> = ( result: T, newState: ParserState<T, U> ) => ParserState<T, U>;
    type MapCallback<T> = ( value: T ) => T;
    type MapDataCallback<T, U> = ( data: U ) => U;
    type MapFromDataCallback<T, U> = ( state: StateData<T, U> ) => Parser<T, U>;

    interface Parser<T = string, U = void> {
        static [ 'fantasy-land/of' ]( x: T ): Parser<T, U>;
        static of( x: T ): Parser<T, U>;

        p: ( state: ParserState<T, U> ) => ParserState<T, U>;

        new( p: ( state: ParserState<T, U> ) => ParserState<T, U> );

        [ 'fantasy-land/ap' ]( parserOfFunction: Parser<T, U> ): Parser<T, U>;
        [ 'fantasy-land/chain' ]( fn: ChainCallback<T> ): Parser<T, U>;
        [ 'fantasy-land/map' ]( fn: MapCallback<T> ): Parser<T, U>;

        ap( parserOfFunction: Parser<T, U> ): Parser<T, U>;
        chain( fn: ChainCallback<T> ): Parser<T, U>;
        chainFromData( fn: ChainFromDataCallback<T, U> ): Parser<T, U>;
        errorChain( fn: ErrorChainCallback<T> ): Parser<T, U>;
        errorMap( fn: ErrorMapCallback<T> ): Parser<T, U>;
        fork( targetString: string, errorFn: ForkErrorCallback<T>, successFn: ForkSuccessCallback<T> ): ParserState<T, U>;
        map( fn: MapCallback<T> ): Parser<T, U>;
        mapData( fn: MapDataCallback<T> ): Parser<T, U>;
        mapFromData( fn: MapFromDataCallback<T, U> ): Parser<T, U>;
        run( targetString: string ): ParserState<T, U>;
    }

    interface ArcsecondParsers {
        digit: Parser;
        digits: Parser;
        getData: Parser<T, U>;
        endOfInput: Parser<T, U>;
        letter: Parser;
        letters: Parser;
        succeedWith: Parser.of;
        optionalWhitespace: Parser<T, U>;
        whitespace: Parser<T, U>;
        anyOfString( s: string ): Parser<T, U>;
        anythingExcept( parser: Parser<T, U> ): Parser<T, U>;
        between( leftParser: Parser<T, U> ): ( rightParser: Parser<T, U> ) => ( parser: Parser<T, U> ) => Parser<T, U>;
        char( c: string ): Parser<T, U>;
        choice( parsers: Iterable<Parser<T, U>> ): Parser<T, U>;
        composeParsers( parsers: Iterable<Parser<T, U>> ): Parser<T, U>;
        coroutine( g: () => Generator<any,any,any> ): Parser<T, U>;
        decide( fn: ( state: ParserState<T, U> ) => Parser<T, U> ): Parser<T, U>;
        either( parser: Parser<T, U> ): Parser<T, U>;
        errorMapTo( fn: ( message: string, index: number, data: U ) => string ): Parser<T, U>;
        everythingUntil( parser: Parser<T, U> ): Parser<T, U>;
        fail( errorMessage: string ): Parser<T, U>;
        lookAhead( parser: Parser<T, U> ): Parser<T, U>;
        many( parser: Parser<T, U> ): Parser<T, U>;
        many1( parser: Parser<T, U> ): Parser<T, U>;
        mapTo( fn: ( data: T ) => T ): Parser<T, U>;
        mapData( fn: ( data: U ) => U ): Parser<T, U>;
        namedSequenceOf( pairedParsers: { [ key: string ]: Parser<T, U> } ): Parser<T, U>;
        parse( parser: Parser<T, U> ): Parser<T, U>;
        pipeParsers( parsers: Iterable<Parser<T, U>> ): Parser<T, U>;
        possibly( parser: Parser<T, U> ): Parser<T, U>;
        recursiveParser( parserThunk: () => Parser<T, U> ): Parser<T, U>;
        regex( re: RegExp ): Parser<T, U>;
        sepBy( parser: Parser<T, U> ): ( parser: Parser<T, U> ) => Parser<T, U>;
        sepBy1( parser: Parser<T, U> ): ( parser: Parser<T, U> ) => Parser<T, U>;
        sequenceOf( parsers: Iterable<Parser<T, U>> ): Parser<T, U>;
        setData( x ): Parser<T, U>;
        skip( parser: Parser<T, U> ): Parser<T, U>;
        str( s: string ): Parser<T, U>;
        takeLeft( parser: Parser<T, U> ): ( parser: Parser<T, U> ) => Parser<T, U>;
        takeRight( parser: Parser<T, U> ): ( parser: Parser<T, U> ) => Parser<T, U>;
        tapParser( fn: ( state: ParserState<T, U> ) => Parser<T, U> ): Parser<T, U>;
        toPromise( result: ParserState<T, U> ): Promise<T>;
        toValue( result: ParserState<T, U> ): T;
        withData( parser: Parser<T, U> ): Parser<T, U>;
    }

    type ArcsecondStatic = ArcsecondParsers;
}

declare const arcsecond: Arcsecond.ArcsecondStatic;

declare module "arcsecond" {
    export = arcsecond;
}
```

**Comment by stephen-smith** [comment] 2019-12-12 02:33
> I've never actually written a .d.ts file from scratch before. I typically just code in TypeScript and let the compiler generate them.

I actually think this is a better way to go.  Use tsc with `declaration: true` and `allowJs: true` and just use what it generates.  Maybe rename some \*.js files to \*.ts if you can find some that don't cause any errors from `tsc` -- TypeScript is supposed to be syntactically a superset of JavaScript, so you shouldn't be *required* to change the code.

If you can figure out how to make it part of the build process, even better, so you don't have to worry about the manual code and the manual type declarations falling out-of-sync if you have manual code and automatic type declarations.

(Not to downplay the value of what you've provided so far.)

**Comment by IMax153** [comment] 2019-12-16 22:08
@jeffrose Hey Jeff, I have based my own type declarations off the scaffold you provided above. 

I am definitely no expert, as I have not written a type declaration file before either. I typically code in TS and let the compiler do the rest as well. However, I think there may be a few issues with the declarations above. For example, I am fairly certain that interfaces in TS will not allow you to create static declarations. In addition, I think there are opportunities for allowing TS to infer the result type of parsers. In addition, I think if the `.d.ts` file is declared within the library itself and has the same name as the file it is declaring types for, we can avoid the module-specific syntax. 

@francisrstokes Francis, would you be open to a PR with a rough draft of a type declarations file that we could all edit?

**Comment by jeffrose** [comment] 2019-12-17 13:37
@IMax153 I actually looked at popular @types files and followed a similar pattern. I am certain some of the declarations do not match up yet. I started this file fairly early on before I knew arcsecond as well as I do now, and I'm still no expert.

**Comment by francisrstokes** [comment] 2019-12-17 13:57
Hey all,

I'm glad to see this topic getting some traction! I agree that @jeffrose 's approach looks good. I think the main thing we're missing is the ability to type the errors/error transformations in the generics, but otherwise this is the way to go. @jeffrose I'm happy to use yours as a base PR for now, where we can all collaborate in this issue and try to get it to the right place. That sound good?

**Comment by IMax153** [comment] 2019-12-17 15:13
@jeffrose Yea that would actually be really interesting! Since I have never written a declaration file either, I have no idea of certain syntax is allowed in a `.d.ts` file versus a `.ts` file which is why I brought up the points above. I hope that I didn't come across as discounting the work that you have done on this. If I did, I truly apologize, it was not my intent.

@francisrstokes That sounds excellent! Happy to use Jeff's definitions as a starting point.

I will at least share my definitions for `Parser` and `ParserState` below both for discussion and in case the TS compiler prevents us from defining the `Parser` as an interface with a constructor and static methods. I also added support for error transformations to be compatible with those aspects of the library that work with the error state. However, there is definitely a lot of room for improvement.

```typescript
type MapCallback<A, B> = (result: A) => B;
type MapFromDataCallback<R, A, B> = (state: ParserState<R, A>) => B;
type ChainCallback<A, B> = (result: A) => Parser<B>;
type ChainFromDataCallback<R, A, B> = (state: ParserState<R, A>) => Parser<B, A>;
type ErrorChainCallback<R, A, B> = (state: StateWithError<R, A>) => Parser<B, A>;
type ForkErrorCallback<T, R, D> = (error: string, newState: StateWithError<T, D>) => R;
type ForkSuccessCallback<T, R, D> = (result: T, newState: StateWithoutError<T, D>) => R;

interface ParserState<R = string, D = void, E = string> {
  isError: boolean;
  error: E | null;
  target: string;
  data: D | null;
  index: number;
  result: R | null;
}

type StateWithError<R = string, D = void> = ParserState<R, D> & { isError: true };
type StateWithoutError<R = string, D = void> = ParserState<R, D> & { isError: false };

export class Parser<R = string, D = void, E = string> {
  static ['fantasy-land/of']<R>(x: R): Parser<R>;
  static of<R>(x: R): Parser<R>;

  public constructor(p: <R2, D2, E2>(state: ParserState<R, D, E>) => ParserState<R2, D2, E2>);

  public ['fantasy-land/map']<A, B>(mapFn: MapCallback<A, B>): Parser<B, D>;
  public map<B>(mapFn: MapCallback<R, B>): Parser<B, D>;

  public mapFromData<B>(mapFromDataFn: MapFromDataCallback<R, D, B>): Parser<B, D>;

  public ['fantasy-land/chain']<B>(chainFn: ChainCallback<R, B>): Parser<B, D>;
  public chain<B>(chainFn: ChainCallback<R, B>): Parser<B, D>;

  public chainFromData<B>(chainFromDataFn: ChainFromDataCallback<R, D, B>): ReturnType<ChainFromDataCallback<R, D, B>>;

  public errorChain<B>(errorChainFn: ErrorChainCallback<R, D, B>): ReturnType<ErrorChainCallback<R, D, B>>;

  public ['fantasy-land/ap'](parser: Parser): Parser<R, D>;
  public ap(parser: Parser): Parser<R, D>;

  public fork<ER, SR>(
    target: string,
    onErrorFn: ForkErrorCallback<R, ER, D>,
    onSuccessFn: ForkSuccessCallback<R, SR, D>
  ): StateWithError<ER, D> | StateWithoutError<SR, D>;

  public run(target: string): ParserState<R, D>;

  private p<R2, D2, E2>(state: ParserState<R, D, E>): ParserState<R2, D2, E2>;
}
```

**Comment by francisrstokes** [comment] 2019-12-17 16:11
Awesome, I see that there is a lot of overlap here. The other thing I forgot to mention is that while the `target` is always string in the case of the main arcsecond library, the binary version (which is not working with 2.x yet) has a different type for target. Parsers like `sequenceOf`, `many`, and `sepBy` are higher-order, and not concerned with the implementation details of what the target actually is, so we should probably account for that in the generics too.

**Comment by jeffrose** [comment] 2019-12-17 17:21
@IMax153 If you look at my example, I have the constructor and static methods declared in the interface using `new` and `static`.

@francisrstokes My use of generics was trying to account for non-string input, though I set `string` as the default, hence the `<T = string>`.  We could keep `Parser` generic, e.g. `Parser<T>` and then extend it, e.g. `interface StringParser extends Parser<string>`, for the base library. The binary version could extend `Parser` with a different type.

I will submit a pull request later today.

**Comment by IMax153** [comment] 2019-12-17 17:55
@jeffrose The problem is that, while interfaces **can** be marked as *newable*, their methods **cannot** be directly marked  as `static`. See [this](https://stackoverflow.com/questions/13955157/how-to-define-static-property-in-typescript-interface/43674389) thread, and the example below from the TS playground. I also checked the [TS repository](https://github.com/microsoft/TypeScript/issues/14600), and there have been several issues raised around static interface methods, but has not been implemented as of yet.

<img width="548" alt="interface_static" src="https://user-images.githubusercontent.com/38051499/71020621-add32500-20ca-11ea-8abd-6a5ea0ab59fe.png">

If the `static` modifier was removed from the method within the interface, then the interface would be valid, but we would only gain access to the method upon constructing a `new` instance of `Parser`, as opposed to the method being accessible from the `Parser` function itself.

**Comment by jeffrose** [comment] 2019-12-18 15:41
As part of my TypeScript experiment and trying to clean up the declaration file a little, I fell into a rabbit hole regarding the Fantasy Land interfaces. It seems you cannot accurately declare some of those interfaces in TypeScript. Take `Functor` for example. There are [implementations](https://github.com/cbowdon/TsMonad/blob/master/src/monad.ts#L95) running around but apparently they [are](https://github.com/fantasyland/fantasy-land/issues/140#issuecomment-218876350) [wrong](https://medium.com/@maxbendick/functor-folly-why-there-isnt-a-fantasy-land-typescript-interface-c28b0644d428). Now having said that, these implementations and issues are a few years old. There may be a way to achieve this in TypeScript now but that will require a little more research.

**Comment by Avaq** [comment] 2019-12-18 15:56
@jeffrose As far as I'm aware, there still is no way to represent these in TypeScript without using some abstraction in TypeScript to represent ADTs. A good example of a lib using a custom ADT representation is [fp-ts](https://github.com/gcanti/fp-ts). 

> A distinctive feature of fp-ts with respect to other functional libraries is its implementation of Higher Kinded Types, which TypeScript doesn't support natively.

The downside of this kind of approach is that TypeScript definitions outside of fp-ts don't understand these types.

In [Fluture](https://github.com/fluture-js/Fluture), I made the trade-off of providing [specialized types for `map`](https://github.com/fluture-js/Fluture/blob/9e8084eefb08c72d0f65352445a80a4791e60983/index.d.ts#L133-L139) and such which know about that types that Fluture knows about, meaning TypeScript does not know that these dispatchers actually work on *any* FL-compatible type. This is essentially the same thing your typings from above are doing.

**Comment by RGFTheCoder** [comment] 2020-09-16 20:22
Are the types working yet?

**Comment by francisrstokes** [comment] 2021-07-04 08:49
I think we can finally almost close this issue with #70. If you're here and looking for TS support (and 4.0.0 isn't out yet), you can try `arcsecond@next`

**Closed** 2021-07-11 18:43 UTC
